### ISSUE TITLE
Разработка моделей окружения

### ISSUE THREAD

**Issue by FractalHenry** [ArgentumAuri/Team8_PhysicsIsland#1]
Обязательное:
  - [x] Острова
  - [x] Камни
  - [x] Деревья
  - [x] Трава
  - [x] Плитки перехода между островами
  - [x] Кусты

Дополнительное(если будет время):
  - [ ] Ограничители перемещения(заборы, стены, пр.)
  - [ ] Предметы экстерьера

**Comment by Paulina8961** [comment]
https://drive.google.com/drive/folders/1oP8bv9LibxnYyFaKye3Rr0UpNBkb4k_R?usp=sharing - деревья

**Comment by FractalHenry** [comment]
https://drive.google.com/drive/folders/15CWOSvS7_O1cnkQj0HGgkGr-sDjEG5GM - облака, камни, кусты
