### ISSUE TITLE
Разработка моделей головоломок

### ISSUE THREAD

**Issue by FractalHenry** [ArgentumAuri/Team8_PhysicsIsland#5]
Общее:
  - [x] Кабель
  - [x] Рычаг
  - [x] Кнопка
  - [x] Светильники

Остров 1:
  - [x] предохранительный ящик   
  - [x] предохранитель
  - [x] корпус головоломки

Остров 2:
  - [x] Сосуд
  - [x] Весы
  - [x] Веса на весы

Остров 3:
  - [x] Сундук
  - [x] Пиктограммы для сундука(луна, солнце, ветер)

Остров 4  и 5:
  - [x] Точка входа
  - [x] Точка выхода
  - [x] Лазер
  - [x] Зеркало
  - [x] Выход

Цветовые палитры:
  - [x] Вариация 1
  - [x] Вариация 2

**Comment by FractalHenry** [comment]
https://drive.google.com/drive/folders/1f8VDqXauYvZa0oXOmS5evMdX4qq_HxdJ - Палитры

**Comment by Paulina8961** [comment]
https://drive.google.com/drive/folders/139nZHM_hjt00_WAS9_xTRjYZmA5FZAeM?usp=sharing - сундук

**Comment by FractalHenry** [comment]
https://drive.google.com/drive/u/0/folders/15CWOSvS7_O1cnkQj0HGgkGr-sDjEG5GM - все модели
