### ISSUE TITLE
Экономика

### ISSUE THREAD

**Issue by FractalHenry** [ArgentumAuri/Team8_PhysicsIsland#6]
- [x] Расходы на разработку
- [x] Доска задач

**Comment by Paulina8961** [comment]
https://docs.google.com/spreadsheets/d/1t5X2e5HIC-DY4oDM4YXymdYhMnXLfwYc/edit?usp=sharing&ouid=101912918273550588717&rtpof=true&sd=true - расчеты

**Comment by Paulina8961** [comment]
https://drive.google.com/file/d/1MRpecmlYnegdDT5FOeWRGdVUdD1mJ71r/view?usp=sharing - доска задач
